### ISSUE TITLE
copy-paste: vol 2, Factual Results of the Obstruction Investigation

### ISSUE THREAD

**Issue by iandennismiller** [iandennismiller/mueller-report#4]
Source code: `src/volume-2/factual-results.tex`

- [ ] copy and paste all text from source document
- [ ] use [LaTeX document conventions](https://github.com/iandennismiller/mueller-report#document-source-code-conventions)
- [ ] manually enter any text that does not copy
- [ ] add blank footnotes using [footnote template](https://github.com/iandennismiller/mueller-report#footnote-template)
- [ ] add redactions using [redaction template](https://github.com/iandennismiller/mueller-report#redacting-template)

**Comment by ohexel** [comment]
I can work on this.

**Comment by iandennismiller** [comment]
Thank you, @ohexel !  It's yours!

**Comment by iandennismiller** [comment]
Hey @ohexel  - how's it going on this?
I know this task is a lot of pages.  Do you want to try breaking up this task into smaller sub-tasks?  I can potentially help out with this work.

**Comment by ohexel** [comment]
Yes, I've been swamped this week. Should be better starting tomorrow. If
you can split out some of the later sections and take them on, that would
speed things up. For example, starting with "\subsection{The President’s
Efforts to Prevent Disclosure of Emails About the June 9, 2016 Meeting
Between Russians and Senior Campaign Officials}." That being said, I'm
happy to do all of it. But it might take a little longer.

**Comment by iandennismiller** [comment]
That sounds good.  I will start working in parallel, this evening.  I will start with the subsection you mentioned; that will be the first subsection that I begin copy-pasting.
Thanks for your help - and thank you for the update!

**Comment by iandennismiller** [comment]
Just a heads up - I pushed my changes to the file `factual-results.tex`.
This should not conflict with your work because I think all my changes occur after the section heading we discussed.

**Comment by iandennismiller** [comment]
Hey @ohexel - I just finished some other work and I could take on a little more of this task, depending on where you are.  Would that be helpful?  The truth is, this section is something like 70% of the entire volume - so it was way too big to be a single task, in the first place.
At any rate, we could split the task again.  Let me know.

**Comment by ohexel** [comment]
I'm working on it right now. Let me see how far I get today and I will let
you know.

**Comment by iandennismiller** [comment]
Hey @ohexel - Would you mind submitting a pull request with your progress? I need to close this issue and move on to the footnotes. I'm going to start tomorrow, 5/7/2019, at about 8pm EDT so please share whatever you've got before then - otherwise, I'll just do it from the beginning. No hard feelings; I'm also a PhD student and I know how it goes. I appreciate all your contributions!

**Comment by ohexel** [comment]
I'll do that. I realized I had started on the executive summary, not the
actual chapter. So very little actual progress. And yes, I did overestimate
my availability.
