### ISSUE TITLE
proofer: vol. 1, executive summary

### ISSUE THREAD

**Issue by ascherer** [iandennismiller/mueller-report#57]
Source code: `src/volume-1/executive-summary.tex` et. al.

- [x] ~~Fix non--end-of-sentence fullstop after abbreviations like `St.~Petersburg`, `Trump Jr.\ `, and `Ms.~Veselnitskaya`.~~
- [x] Fix end-of-sentence fullstop after abbreviations like `DNC\null.`

This applies to all parts and source files with such elements.

**Comment by iandennismiller** [comment]
👍

**Comment by iandennismiller** [comment]
Just double-checking: did your pull close this issue or are the end-of-sentence fullstops yet to be fixed?

**Comment by ascherer** [comment]
Done.
