### ISSUE TITLE
copy-paste: vol 1, Prosecution and Declination Decisions

### ISSUE THREAD

**Issue by iandennismiller** [iandennismiller/mueller-report#8]
Source code: `src/volume-1/decisions.tex`

- [x] copy and paste all text from source document
- [x] use [LaTeX document conventions](https://github.com/iandennismiller/mueller-report#document-source-code-conventions)
- [x] manually enter any text that does not copy
- [ ] add blank footnotes using [footnote template](https://github.com/iandennismiller/mueller-report#footnote-template)
- [x] add redactions using [redaction template](https://github.com/iandennismiller/mueller-report#redacting-template)

**Comment by ohexel** [comment]
I would be willing to work on this.

**Comment by iandennismiller** [comment]
Awesome!  The file is `src/volume-1/decisions.tex`.

How can I help you to get started?

**Comment by ohexel** [comment]
Is there a preferred format for itemized lists or do we follow the report?

**Comment by iandennismiller** [comment]
Use `\begin{itemize}` and then `\item`

LaTeX will convert that to a dot or list glyph when it renders.

**Comment by iandennismiller** [comment]
Also, please take a look at the other `.tex` files in the directory.  There are some examples of itemized lists, if you search for `itemize`
